# Generated by Django 5.1.1 on 2024-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_photo_car_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
