# Generated by Django 5.1.1 on 2024-10-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="foto",
        ),
    ]
